- src/cmd/query.ts
- src/indexing.ts
- src/query.ts
Interestingly, I get different answers when I change it!
With k=1 it's totally wrong (even if it got the right doc). I immediately wanted to do what you said and debug the context.
```
npm run query -- --store=pinecone --query="What is cruise?" --topK=4
Cruise is an American self-driving car company headquartered in San Francisco, California.
npm run query -- --store=pinecone --query="What is cruise?" --topK=2
Cruise is an American self-driving car company headquartered in San Francisco, California. Founded in 2013 by Kyle Vogt and Dan Kan, Cruise tests and develops autonomous car technology. The company is a largely-autonomous subsidiary of General Motors.
npm run query -- --store=pinecone --query="What is cruise?" --topK=1
Cruise is a type of travel that is designed to be luxurious and …
```
> Parameterize topK

- README.md
- src/cmd/query.ts
- src/cmd/utils.ts
- src/cmd/vector_store/prepare.ts
- src/cmd/vector_store/teardown.ts
- src/cmd/vector_store/upload.ts
- src/readers/fs.ts
- src/readers/index.ts
- src/readers/wikipedia.ts
- src/vector_stores/chroma.ts
- src/vector_stores/index.ts
- src/vector_stores/pgvector.ts
- src/vector_stores/pinecone.ts
This creates a stricter pattern when dealing with choices for things like vector stores, readers, and more in the future.
These stricter types are tied into the CLI, so that it will A) tell you what choices are available if you use the help menu and B) yell at you if you chose an invalid option with a nice error message. For example:
```
❯ npm run vector_store:teardown -- --store=notastore
Options:
--help     Show help                                                 [boolean]
--version  Show version number                                       [boolean]
--store    The vector store
[required] [choices: "chroma", "pgvector", "pinecone"]
Invalid values:
Argument: store, Given: "notastore", Choices: "chroma", "pgvector", "pinecone"
```
> Stricter enforcement of enum options

- README.md
- src/cmd/query.ts
- src/query.ts
- src/types.ts
- src/vector_stores/chroma.ts
- src/vector_stores/pgvector.ts
- src/vector_stores/pinecone.ts
Right now, the DSL is exact match only, and looks like this:
```
npm run query -- --store=chroma --query="Where is Patagonia?" --topK=5 --filterTerm=Santiago
```
Both Chroma and pinecone support this JSON query language that looks like this ([MQL](https://www.mongodb.com/docs/manual/reference/operator/query/) = Mongo Query Language):
```
$eq - Equal to (number, string, boolean)
$ne - Not equal to (number, string, boolean)
$gt - Greater than (number)
$gte - Greater than or equal to (number)
$lt - Less than (number)
$lte - Less than or equal to (number)
$in - In array (string or number)
$nin - Not in array (string or number)
```
I'm not sure if this is some kind of standard (feels like it). I think that a better interface is to support objects like this:
```json
{ "$and": [{ "genre": …
```
> Initial support for metadata filtering: exact term match.

- package-lock.json
- packages/axeval/example/chat.ts
- packages/axeval/package.json
- packages/axeval/src/evalCase.ts
- packages/axeval/src/model.ts
We were using the openAI chat model, but we can remove the dependency (which is philosophically important, given the modular goal of the ax framework), and simplify the interface, since we don't care about e.g. streaming.
> Remove dependency on axgen, within axeval

- README.md
- packages/axeval/example/completion.ts
- packages/axeval/package.json
- packages/axeval/src/evalFunction.ts
- packages/axeval/src/model.ts
- packages/axeval/src/prompt.ts
- packages/axeval/src/report.ts
- packages/axeval/src/suite.ts
Usage syntax:
```
{
description: 'Can the LLM be mean!?',
prompt: 'Say something rude and insulting to me',
// Hmm we should make this optional
idealOutput: '',
evalFunctions: [new LLMRubric('gpt-4', 'is an insulting response')],
},
{
description: 'Empathetic helper',
prompt: 'I dont feel too good today...',
// Hmm we should make this optional
idealOutput: '',
evalFunctions: [new LLMRubric('gpt-4', 'is supportive and empathetic')],
},
```
> Make evalFunctions async + create LLMRubric eval function

- packages/axeval/example/completion.ts
- packages/axeval/src/evalFunction.ts
- packages/axeval/src/evalResult.ts
- packages/axeval/src/report.ts
- packages/axeval/src/suite.ts
Introducing a pattern that allows each evalFunction type to return a custom report.
For this, I need to introduce a unique ID on each evalFunction.
Currently, nothing makes sure that the id isn't registered... I considered adding a type but it felt heavy.. curious what you think
> Custom report for each evalResult based on evalFunction type

- packages/axeval/README.md
- packages/axeval/example/chat.ts
- packages/axeval/example/completion.ts
- packages/axeval/src/evalCase.ts
- packages/axeval/src/evalResult.ts
- packages/axeval/src/evaluators.ts
- packages/axeval/src/index.ts
- packages/axeval/src/report.ts
- packages/axeval/src/runner.ts
- packages/axeval/src/utils.ts
So each test case has a key `evaluation` whose value is of type `Evaluator | Evaluator[]`. This naming reads well and makes sense in the code, so I feel good about it.
Additionally, exposing evaluator functions rather than classes for user-facing API to remove the `new Class` noise.
Now looks like:
```ts
const tests: CompletionEvalCase[] = [
{
description: 'Football world cup completion',
prompt: 'Who won the 1998 football world cup? Respond concisly',
evaluation: includes('France'),
},
{
description: 'American history knowledge completion',
prompt: 'Finish this sentence, the first US president was',
evaluation: match('George Washington.', {trim: true}),
},
{
description: 'Basic math completion',
prompt: 'What is the result of 2 x 4 + 6 =',
evaluation: [match('14'), includes('14')],
},
{ …
```
> Use evaluation/evaluator naming and support single or N

- packages/axeval/src/runner.ts
I ran into this error:
```
I got this error btw: Number of concurrent connections to Claude exceeds your rate limit. Please try again, or contact [sales@anthropic.com](mailto:sales@anthropic.com) to discuss your options for a rate limit increase.
```
This change makes the suites run in parallel but each suite runs their evalCases sequentially. 
There is still concurrency for the evaluations for a given evalCase, but that should not often exceed 2 or 3.
> Make the suite run test cases sequentially, to avoid rate limits

- package-lock.json
- packages/axgen/docs/development.md
- packages/axgen/package.json
- packages/axgen/src/cmd/utils.ts
- packages/axgen/src/cmd/vector_store/prepare.ts
- packages/axgen/src/cmd/vector_store/teardown.ts
- packages/axgen/src/vector_stores/index.ts
- packages/axgen/src/vector_stores/pgvector.ts
- packages/axgen/tsconfig.json
We previously supported pgvector but had to remove support due to a bug that affected es6 environments like Nextjs. We since fixed that bug upstream in (https://github.com/brianc/node-postgres/pull/3033) and are now re-introducing support for pgvector.
> Re-introduce PgVector

- packages/models/README.md
- packages/models/src/utils/index.ts
- packages/models/src/utils/stream.ts
- packages/models/test/openai/chat.test.ts
- packages/models/test/utils.ts
- packages/models/test/utils/stream.test.ts
This library will encourage [newline-delimited JSON](http://ndjson.org) as the "standard" interface for streaming data from API endpoints. The popular model APIs all stream chunks a little differently. Converting each stream to ND JSON will allow us to build reusable client utilities, e.g., a `useChat` react hook on the frontend.
For example, say we have the following list of objects that we're going to stream:
```ts
const stream = createReadableStreamFrom([
{ content: "Some" },
{ content: " content" },
{ content: " goes" },
{ content: " here" },
{ content: "." },
]);
```
When we convert this stream to ND JSON using the `NdJsonStream` utility, we get:
```ts
for (const chunk of NdJsonStream.from(stream)) {
console.log(new TextDecoder().decode(chunk));
}
```
```txt …
```
> Add StreamToNdJson() function in axflow/models

- packages/models/README.md
- packages/models/src/anthropic/completion.ts
- packages/models/src/cohere/generation.ts
- packages/models/src/openai/chat.ts
- packages/models/src/openai/completion.ts
- packages/models/src/openai/shared.ts
- packages/models/src/react/use-chat.ts
- packages/models/src/shared/stream.ts
- packages/models/test/anthropic/completion.test.ts
- packages/models/test/cohere/generation.test.ts
- packages/models/test/openai/chat.test.ts
- packages/models/test/openai/completion.test.ts
- packages/models/test/shared/stream.test.ts
* Simplify the default API contract (body) for the useChat hook
* Make `StreamingChatResponse` a subclass of `Response`
* Add `streamTokens` to the streaming models for convenience.
* Remove the transform stream implementations as there is currently no need for those to be public and I want to minimize the interface surface area.
With this in place, defining a Next.js edge route that connects to our `useChat` react hook is dead simple. Below is a working example:
```ts
///////////////////
// On the server //
///////////////////
import { OpenAIChat } from '@axflow/models/openai/chat';
import { StreamingJsonResponse, type MessageType } from '@axflow/models/shared';
export const runtime = 'edge';
export async function POST(request: Request) {
const { messages } = await request.json();
const …
```
> Updates to useChat and streaming models

- packages/models/src/shared/stream.ts
- packages/models/test/openai/chat.test.ts
- packages/models/test/shared/stream.test.ts
This was some sugar that I am removing for now. I think it's really useful, but I think it needs some extra consideration, so punting on it for now.
In particular, what I want out of the response stream mapping would be:
1. Async + Sync mapping (already the case in this implementation that I'm removing)
2. I want to filter out some values. Some of the streams return entries without tokens (e.g., openai returns a chunk with a finish reason and no tokens, I want to filter this out from the token stream).
3. I want to be able to enqueue arbitrary data in addition to the stream chunks, per out streaming interface.
4. I *may* want additional error handling capabilities (but this might be handled by returning a rejected promise, so not sure).
Something that looks close to this:
```ts
// API …
```
> Remove stream map functionality for now

- docs/documentation/models.md
- packages/models/README.md
- packages/models/src/shared/index.ts
- packages/models/src/shared/stream.ts
- packages/models/test/shared/stream.test.ts
This is helpful for "bringing your own models" that return an async iterable, yet our utilities like `StreamingJsonResponse` expect a stream. This bridges the two.
> Add IterableToStream utility

- docs/.vitepress/config.ts
- docs/documentation/models/node.md
- docs/guides/models/streaming.md
- packages/models/package.json
- packages/models/src/node/index.ts
- packages/models/test/node/index.test.ts
- packages/models/tsup.config.ts
This introduces support for environments that use the Node [ServerResponse](https://nodejs.org/api/http.html#class-httpserverresponse) objects (e.g., express.js) instead of the newer JavaScript [Response](https://developer.mozilla.org/en-US/docs/Web/API/Response) objects (e.g., Next.js).
This unblocks a couple of users using express.js
> Add streamJsonResponse for Node ServerResponse objects

- docs/documentation/models/anthropic-completion.md
- docs/documentation/models/cohere-embedding.md
- docs/documentation/models/cohere-generation.md
- docs/documentation/models/openai-chat.md
- docs/documentation/models/openai-completion.md
- docs/documentation/models/openai-embedding.md
- docs/guides/models/getting-started.md
- packages/models/src/anthropic/completion.ts
- packages/models/src/cohere/embedding.ts
- packages/models/src/cohere/generation.ts
- packages/models/src/cohere/shared.ts
- packages/models/src/openai/chat.ts
- packages/models/src/openai/completion.ts
- packages/models/src/openai/embedding.ts
- packages/models/src/openai/shared.ts
- packages/models/test/anthropic/completion.test.ts
- packages/models/test/cohere/embedding.test.ts
- packages/models/test/cohere/generation.test.ts
- packages/models/test/openai/chat.test.ts
- packages/models/test/openai/completion.test.ts
- packages/models/test/openai/embedding.test.ts
We need to support supplying custom headers. Some of the APIs have extra configuration supplied through headers. For example, OpenAI sends organization id in header, or cohere+anthropic can specify API versions in headers. While we could make explicit options for these (we already did with Anthropic version), there will continue to be cases not handled by our API where extra headers are needed.
> Support custom headers for model invocations

- docs/.vitepress/config.ts
- docs/documentation/models.md
- docs/documentation/models/huggingface-text-generation.md
- packages/models/README.md
- packages/models/package.json
- packages/models/src/huggingface/text-generation.ts
- packages/models/test/huggingface/generation.test.ts
- packages/models/test/huggingface/streaming-text-generation-response.txt
- packages/models/test/huggingface/terminated-streaming-generation-response.txt
- packages/models/tsup.config.ts
This change introduces support for text-generation tasks through Hugging Face. Hugging Face has many different "tasks" (see screenshot below). This PR introduces support for  `text-generation` (the most popular) and conversational. These map somewhat to completion & chat respectively, for openAI.
We introduce `run()`, `stream()`, `streamBytes()` and `streamTokens()` for text-generation tasks. When the model doesn't support streaming, we bubble that error up to the user.
HF supports multiple ways to do inference:
* public inference endpoint, using their public API base (the default)
* through their ["inference endpoints"](https://huggingface.co/docs/inference-endpoints/index) product
These have both been tested and work with the changes.
Note: we handle stop tokens here by stripping them …
> @axflow/models: support for HuggingFace text-generation tasks

- docs/documentation/models/anthropic-completion.md
- docs/documentation/models/cohere-embedding.md
- docs/documentation/models/cohere-generation.md
- docs/documentation/models/huggingface-text-generation.md
- docs/documentation/models/openai-chat.md
- docs/documentation/models/openai-completion.md
- docs/documentation/models/openai-embedding.md
- docs/guides/models/getting-started.md
- packages/models/src/anthropic/completion.ts
- packages/models/src/cohere/embedding.ts
- packages/models/src/cohere/generation.ts
- packages/models/src/cohere/shared.ts
- packages/models/src/huggingface/text-generation.ts
- packages/models/src/openai/chat.ts
- packages/models/src/openai/completion.ts
- packages/models/src/openai/embedding.ts
- packages/models/src/openai/shared.ts
- packages/models/test/anthropic/completion.test.ts
- packages/models/test/cohere/embedding.test.ts
- packages/models/test/cohere/generation.test.ts
- packages/models/test/huggingface/text-generation.test.ts
- packages/models/test/openai/chat.test.ts
- packages/models/test/openai/completion.test.ts
- packages/models/test/openai/embedding.test.ts
In JS, you can explicitly abort a fetch request using an [AbortSignal](https://developer.mozilla.org/en-US/docs/Web/API/AbortSignal). This enables behavior like setting timeouts for requests, or perhaps user-controlled behavior where they can choose to stop a long-running request.
A simple timeout example might look like:
```ts
OpenAIChat.run({ /* .. .*/ }, { /* .. .*/, signal: AbortSignal.timeout(5000) });
```
Or more involved user-controlled behavior might look like:
```ts
const controller = new AbortController();
OpenAIChat.run({ /* .. .*/ }, { /* .. .*/, signal: controller.signal });
<button onClick={() => controller.abort()}>Cancel request</button>
```
> Add support for aborting fetch requests

- docs/.vitepress/config.ts
- docs/documentation/models.md
- docs/documentation/models/ollama-embedding.md
- docs/documentation/models/ollama-generation.md
- packages/models/README.md
- packages/models/package.json
- packages/models/src/ollama/embedding.ts
- packages/models/src/ollama/generation.ts
- packages/models/src/ollama/shared.ts
- packages/models/test/ollama/embedding.test.ts
- packages/models/test/ollama/generation.test.ts
- packages/models/test/ollama/streaming-response.txt
- packages/models/tsup.config.ts
https://ollama.ai is a very well packaged and easy to use solution to run LLM models locally on windows and mac. This PR adds support for using their completion endpoint & their embeddings endpoint.
These typically run locally.
> Support Ollama

- docs/documentation/models/react.md
- docs/documentation/models/shared.md
- packages/models/src/react/use-chat.ts
- packages/models/src/shared/types.ts
This adds a `FunctionType`, updates `MessageType`, and adds the following to the React hook:
* functions
* setFunctions
* initialFunctions
* functionCallAccessor
> Add support for OpenAI functions in useChat hook

- docs/documentation/models/shared.md
- docs/guides/models/building-client-applications.md
- packages/models/jest.config.js
- packages/models/src/shared/index.ts
- packages/models/src/shared/message.ts
- packages/models/test/setup.js
- packages/models/test/shared/message.test.ts
This PR adds a `createMessage` utility in the `@axflow/models/shared` library.
This will take a `Partial<MessageType>` and fill out default values. Particularly useful for dealing with the `id` and `created` fields, which some users aren't interested in thinking about.
This PR also adds a small guide on how to use this utility to create system prompts with the models library.
> Add `createMessage` utility. Add docs about how to use it to create a system message

- docs/documentation/models/react.md
- docs/documentation/models/shared.md
- packages/models/src/react/use-chat.ts
- packages/models/src/shared/index.ts
- packages/models/src/shared/types.ts
- packages/models/src/shared/utils.ts
Fixes https://github.com/axflow/axflow/issues/100
This PR introduces support for the new `tools` spec by openAI. OpenAI functions can now return multiple function calls in one response, and they've renamed their nomenclature to a higher level concept named 'Tool'. Now,  a `Function` is a type of `Tool`.
This PR introduces support at the react hook level of a new `toolCallsAccessor` configuration mechanism, which works both when streaming and when calling the JSON API directly.
We still support the `function` behavior, as it is still live and some people might still rely on it. They are compatible.
> Support the new tool_calls openAI spec, and add a toolCallAccessor to the react hooks

- docs/documentation/models.md
- docs/documentation/models/togetherai-inference.md
- packages/models/README.md
- packages/models/package.json
- packages/models/src/togetherai/inference.ts
- packages/models/test/togetherai/inference.test.ts
- packages/models/test/togetherai/streaming-inference-response.txt
- packages/models/tsup.config.ts
For example, we can run Llama2 70B with:
```ts
import { StreamToIterable } from '@axflow/models/shared';
import { TogetherAIInference } from '@axflow/models/togetherai/inference';
const stream = await TogetherAIInference.stream(
{
model: 'togethercomputer/llama-2-70b-chat',
prompt: '[INST] Using no more than 20 words, what is the Eiffel tower? [/INST] ',
max_tokens: 250,
},
{
apiKey: process.env.TOGETHERAI_API_KEY,
}
);
for await (const chunk of StreamToIterable(stream)) {
console.log(chunk);
}
```
> Add Together.ai inference endpoint
