.env.example, README.md, package-lock.json, package.json, src/cmd/utils.ts, src/cmd/vector_store/prepare.ts, src/cmd/vector_store/teardown.ts, src/vector_stores/pgvector.ts, tsconfig.json
The quality is surprisingly poor, still investigating that.
However I believe that all the mechanisms are in place and work correctly. Some improvements to be followed up on.
=> Support for PG vector

src/vector_stores/pgvector.ts
=> Use cosine distance with pgvector

src/query.ts, src/utils.ts, test/utils.test.ts, tsconfig.json
Will want this formatting for more robust prompt functionality.
=> Add template formatter for prompts

src/cmd/vector_store/prepare.ts, src/cmd/vector_store/teardown.ts, src/embedders/index.ts, src/embedders/open-ai-embedder.ts, src/index.ts, src/models/index.ts, src/models/open-ai-completion.ts, src/prompts.ts, src/queries/completion.ts, src/queries/index.ts, src/queries/rag.ts, src/query.ts, src/retrievers.ts, src/sources/file-system.ts, src/sources/index.ts, src/sources/wikipedia.ts, src/splitters/index.ts, src/splitters/markdown.ts, src/splitters/text.ts, src/types.ts, src/utils.ts, src/vector_stores/chroma.ts, src/vector_stores/index.ts, src/vector_stores/pgvector.ts, src/vector_stores/pinecone.ts, test/prompts.test.ts
This is a first pass, we'll need to rework this a bit.
=> Add library exports

src/sources/text-document.ts
This will be useful for uploaded files that are already converted to utf8 encoded strings.
=> Add text-document data source

packages/axeval/example/completion.ts, packages/axeval/src/evalFunction.ts, packages/axeval/src/evalResult.ts, packages/axeval/src/report.ts, packages/axeval/src/suite.ts
Some "fails" that look intuitively correct are hard to understand without this…it has to do with trimming strictness, see below.
=> Print options to increase context in debug mode

packages/axeval/example/chat.ts, packages/axeval/example/completion.ts, packages/axeval/src/evalCase.ts, packages/axeval/src/evalFunction.ts, packages/axeval/src/evalResult.ts, packages/axeval/src/model.ts, packages/axeval/src/report.ts, packages/axeval/src/suite.ts
=> Change from idealOutput to evalFunction arg; report expected

packages/axgen/src/sources/files/pdf.ts, packages/axgen/src/sources/files/txt.ts, packages/axgen/src/sources/text-document.ts, packages/axgen/src/sources/wikipedia.ts, packages/axgen/src/splitters/csv.ts, packages/axgen/src/splitters/markdown.ts, packages/axgen/src/splitters/text.ts, packages/axgen/src/types.ts, packages/axgen/test/splitters/csv.test.ts
I left this off to begin with but starting to have use cases for this now.
=> Add metadata to documents

docs/LICENSE.md, docs/documentation.md, docs/documentation/axeval.md, docs/documentation/axgen.md
The build was failing because it detected broken links.
=> Docs fixes

package-lock.json, packages/axgen/.env.example, packages/axgen/.gitignore, packages/axgen/README.md, packages/axgen/package.json, packages/axgen/src/cmd/utils.ts, packages/axgen/src/cmd/vertexai/chat.ts, packages/axgen/src/cmd/vertexai/text.ts, packages/axgen/src/embedders/index.ts, packages/axgen/src/embedders/vertex-ai-embedder.ts, packages/axgen/src/models/index.ts, packages/axgen/src/models/vertexai/chat.ts, packages/axgen/src/models/vertexai/text.ts, packages/axgen/src/models/vertexai/types.ts, packages/axgen/src/models/vertexai/utils.ts
Address https://github.com/axilla-io/ax/issues/52. Support for the following google language models via VertexAI:
* text-bison
* chat-bison
* textembedding-gecko
See cmd/vertexai/text and cmd/vertexai/chat for example usage.
=> Add support for VertexAI models

packages/axgen/README.md, packages/axgen/package.json, packages/axgen/src/cmd/anthropic.ts, packages/axgen/src/models/anthropic.ts, packages/axgen/src/models/index.ts, packages/axgen/src/templates.ts
Implements Anthropic's models: https://docs.anthropic.com/claude/reference/complete_post
=> Add Anthropic models

packages/axgen/README.md, packages/axgen/package.json, packages/axgen/src/cmd/cohere.ts, packages/axgen/src/models/cohere.ts, packages/axgen/src/models/index.ts
Generate models for now, with more to come.
https://docs.cohere.com/reference/generate
=> Add support for Cohere models

package-lock.json, packages/models/.gitignore, packages/models/LICENSE, packages/models/README.md, packages/models/jest.config.js, packages/models/package.json, packages/models/src/anthropic/completion.ts, packages/models/src/cohere/embedding.ts, packages/models/src/cohere/generation.ts, packages/models/src/openai/chat.ts, packages/models/src/openai/completion.ts, packages/models/src/openai/embedding.ts, packages/models/src/openai/shared.ts, packages/models/src/utils/http.ts, packages/models/src/utils/index.ts, packages/models/src/utils/stream.ts, packages/models/test/anthropic/completion.test.ts, packages/models/test/anthropic/streaming-completion-response.txt, packages/models/test/cohere/embedding.test.ts, packages/models/test/cohere/generation.test.ts, packages/models/test/cohere/streaming-generation-response.txt, packages/models/test/openai/chat.test.ts, packages/models/test/openai/completion.test.ts, packages/models/test/openai/embedding.test.ts, packages/models/test/openai/streaming-chat-response.txt, packages/models/test/openai/streaming-completion-response.txt, packages/models/test/utils.ts, packages/models/tsconfig.json, packages/models/tsup.config.ts
New package for consuming models through a streamlined interface. See README.md for more
=> Introduce @axflow/models

packages/models/src/utils/stream.ts, packages/models/test/utils/stream.test.ts
Additionally, this adds supports for asynchronous and synchronous mapping over stream chunks.
With this in place, streaming from OpenAI to our `useChat` function will be as simple as:
```ts
export async function POST(request: Request) {
const req = await request.json();
const stream = await OpenAIChat.stream(req, { apiKey: OPENAI_API_KEY });
return NdJsonStream.response(stream);
}
```
Or for another one of our supported models, like Cohere
```ts
export async function POST(request: Request) {
const req = await request.json();
const stream = await CohereGeneration.stream(req, { apiKey: COHERE_API_KEY });
return NdJsonStream.response(stream);
}
```
=> Add NdJsonStream.response convenience method

package-lock.json, packages/models/package.json, packages/models/src/react/index.ts, packages/models/src/react/use-chat.ts, packages/models/src/shared/index.ts, packages/models/src/utils/stream.ts, packages/models/tsconfig.json, packages/models/tsup.config.ts
=> Introduce useChat component for @axflow/models

docs/.vitepress/config.ts, docs/documentation/models.md, docs/index.md
I used the README content and added to the sidebar for now.
=> Add models content to doc.axilla.io

docs/.vitepress/config.ts, docs/documentation/models.md, docs/index.md
The docs content is the same as the README of the package for now, I also updated the sidebar, and replaced all mentions of axextract for the moment.
=> Publish axilla docs for @axflow/models

packages/axeval/package.json, packages/axgen/package.json, packages/models/package.json
This happened in a recent PR, adding a script makes it easier to give people a direct way to fix things.
=> Add a npm run format script to help contributors who don't have prettier editor setup

docs/guides/models/building-client-applications.md, packages/models/src/react/use-chat.ts
Enables handling loading and errors when building client applications with `useChat`.
=> Support loading and error states for useChat

docs/documentation/models/react.md, docs/guides/models/building-client-applications.md, packages/models/src/react/use-chat.ts
1. Fix consistency bug with initial state setting
2. Add callback to listen for message updates. This makes it much easier to eg persist message state of a chat
3. Docs updates
=> useChat improvements

docs/documentation/models/react.md, docs/guides/models/building-client-applications.md, packages/models/src/react/use-chat.ts, packages/models/test/azure-openai/chat.test.ts
This supports use cases involving:
1. Reloading the last assistant response
2. Reset to an earlier point in a conversation and replay from there
=> Support reloading assistant messages

docs/documentation/models/react.md, docs/guides/models/building-client-applications.md, packages/models/src/react/use-chat.ts
Submitting/reloading system messages on their own is valid and sometimes desired.
=> Support reloading from system messages in addition to user ones

docs/documentation/models/cohere-embedding.md, packages/models/src/cohere/embedding.ts, packages/models/test/cohere/embedding.test.ts
* https://txt.cohere.com/introducing-embed-v3
* https://twitter.com/1vnzh/status/1720141516620841230?s=20
=> Update to support cohere v3 embedding models

packages/models/src/openai/chat.ts, packages/models/test/azure-openai/chat.test.ts, packages/models/test/azure-openai/streaming-chat-response.txt
OpenAI dev day announced some changes to their API. This implements said changes.
Documentation is [here](https://platform.openai.com/docs/api-reference/chat/object)
We'll need to likely make similar changes to the azure openAI library, but that comes with versioning nuance and will be a separate PR.
[Quick link to the openAI library types](https://github.com/openai/openai-node/blob/2242688f14d5ab7dbf312d92a99fa4a7394907dc/src/resources/chat/completions.ts#L664)
I'm running this integration test locally:
```typescript
describe('openAI inference endpoint', () => {
it('should call run() on the newest GPT4 model', async () => {
const response = await OpenAIChat.run(
{
model: 'gpt-4-1106-preview',
messages: [
{ role: 'system', content: 'be very brief' },
{ role: 'user', content: 'Is the …
```
=> Add new openAI types
